# Generated by Django 6.0.3 on 2026-03-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('transport', 'Transport'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('wages', 'Wages'), ('fuel', 'Fuel'), ('packaging', 'Packaging'), ('maintenance', 'Maintenance'), ('miscellaneous', 'Miscellaneous')], default='miscellaneous', max_length=120),
        ),
    ]
