from django.urls import path
from .views import (
    PurchaseOrderListView,
    PurchaseOrderCreateView,
    PurchaseOrderDetailView,
    PurchaseOrderUpdateView,
    PurchaseOrderLineAddView,
    PurchaseOrderLineUpdateView,
    PurchaseOrderLineDeleteView,
    PurchaseOrderMarkOrderedView,
    PurchaseOrderReceiveView,
    PurchaseOrderReceiptsView,
    PurchaseOrderCancelView,
    PurchaseOrderCreateBillView,
    SupplierBillListView,
    SupplierBillDetailView,
    SupplierBillCancelView,
)

urlpatterns = [
    path("", PurchaseOrderListView.as_view(), name="purchase_list"),
    path("create/", PurchaseOrderCreateView.as_view(), name="purchase_create"),
    path("<uuid:purchase_id>/", PurchaseOrderDetailView.as_view(), name="purchase_detail"),
    path("<uuid:purchase_id>/update/", PurchaseOrderUpdateView.as_view(), name="purchase_update"),
    path("<uuid:purchase_id>/lines/add/", PurchaseOrderLineAddView.as_view(), name="purchase_line_add"),
    path("<uuid:purchase_id>/lines/<uuid:line_id>/", PurchaseOrderLineUpdateView.as_view(), name="purchase_line_update"),
    path("<uuid:purchase_id>/lines/<uuid:line_id>/delete/", PurchaseOrderLineDeleteView.as_view(), name="purchase_line_delete"),
    path("<uuid:purchase_id>/mark-ordered/", PurchaseOrderMarkOrderedView.as_view(), name="purchase_mark_ordered"),
    path("<uuid:purchase_id>/receive/", PurchaseOrderReceiveView.as_view(), name="purchase_receive"),
    path("<uuid:purchase_id>/receipts/", PurchaseOrderReceiptsView.as_view(), name="purchase_receipts"),
    path("<uuid:purchase_id>/cancel/", PurchaseOrderCancelView.as_view(), name="purchase_cancel"),
    path("bills/", SupplierBillListView.as_view(), name="supplier_bill_list"),
    path("bills/<uuid:bill_id>/", SupplierBillDetailView.as_view(), name="supplier_bill_detail"),
    path("bills/<uuid:bill_id>/cancel/", SupplierBillCancelView.as_view(), name="supplier_bill_cancel"),
    path("<uuid:purchase_id>/create-bill/", PurchaseOrderCreateBillView.as_view(), name="purchase_create_bill"),
]
