# Generated by Django 6.0.2 on 2026-03-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='driverlicense',
            table='driver_licenses',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
