# Generated by Django 6.0 on 2026-03-26

from django.db import migrations


def backfill_usernames(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    existing = set(User.objects.values_list("username", flat=True))

    candidates = User.objects.filter(username__isnull=True) | User.objects.filter(username="")
    for user in candidates:
        base = "user"
        if getattr(user, "email", None):
            base = user.email.split("@")[0] or "user"

        candidate = base
        counter = 1
        while candidate in existing:
            candidate = f"{base}{counter}"
            counter += 1

        user.username = candidate
        user.save(update_fields=["username"])
        existing.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(backfill_usernames, migrations.RunPython.noop),
    ]
