# Generated by Django 6.0.3 on 2026-03-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_backfill_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('cashier', 'Cashier'), ('salesperson', 'Salesperson'), ('supervisor', 'Supervisor'), ('admin', 'Admin'), ('deliver_person', 'Delivery_person')], max_length=50),
        ),
    ]
