# Generated by Django 6.0.3 on 2026-03-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('cashier', 'Cashier'), ('salesperson', 'Salesperson'), ('supervisor', 'Supervisor'), ('admin', 'Admin'), ('deliver_person', 'Delivery_person'), ('customer', 'Customer')], max_length=50),
        ),
    ]
