# Generated by ChatGPT on 2026-03-25

from django.db import migrations, models


def copy_selling_to_retail(apps, schema_editor):
    Product = apps.get_model("inventory", "Product")
    for product in Product.objects.filter(retail_price__isnull=True):
        product.retail_price = product.selling_price
        product.save(update_fields=["retail_price"])


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_product_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="retail_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="wholesale_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="wholesale_threshold",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(copy_selling_to_retail, migrations.RunPython.noop),
    ]
