# Generated by ChatGPT on 2026-03-26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_base_units(apps, schema_editor):
    Product = apps.get_model("inventory", "Product")
    ProductUnit = apps.get_model("inventory", "ProductUnit")

    for product in Product.objects.all():
        if ProductUnit.objects.filter(product_id=product.id, is_base_unit=True).exists():
            continue
        ProductUnit.objects.create(
            product_id=product.id,
            unit_name="Base Unit",
            unit_code="base",
            conversion_to_base_unit=1,
            is_base_unit=True,
            retail_price=product.retail_price or product.selling_price,
            wholesale_price=product.wholesale_price,
            wholesale_threshold=product.wholesale_threshold,
            is_active=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_add_pricing_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductUnit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("correlation_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("unit_name", models.CharField(max_length=50)),
                ("unit_code", models.CharField(max_length=32)),
                ("conversion_to_base_unit", models.PositiveIntegerField()),
                ("is_base_unit", models.BooleanField(default=False)),
                ("retail_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("wholesale_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("wholesale_threshold", models.PositiveIntegerField(blank=True, null=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="units", to="inventory.product")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_%(class)s_set", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_%(class)s_set", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name="productunit",
            constraint=models.UniqueConstraint(fields=("product", "unit_code"), name="uniq_product_unit_code"),
        ),
        migrations.AddConstraint(
            model_name="productunit",
            constraint=models.UniqueConstraint(condition=models.Q(("is_base_unit", True)), fields=("product",), name="uniq_product_base_unit"),
        ),
        migrations.AddConstraint(
            model_name="productunit",
            constraint=models.CheckConstraint(condition=models.Q(("conversion_to_base_unit__gt", 0)), name="product_unit_conversion_positive"),
        ),
        migrations.RunPython(create_base_units, migrations.RunPython.noop),
    ]
