# Generated by Django 6.0.3 on 2026-03-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_product_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productunit',
            options={'verbose_name': 'Product Unit', 'verbose_name_plural': 'Product Units'},
        ),
    ]
