# Generated by Django 6.0.3 on 2026-04-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_productunit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
