# Generated by Django 6.0 on 2026-04-09 00:00

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_productunit_cost_price"),
        ("suppliers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSupplier",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("correlation_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("supplier_sku", models.CharField(blank=True, default="", max_length=64)),
                ("supplier_price", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_links",
                        to="inventory.product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_links",
                        to="suppliers.supplier",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Supplier",
                "verbose_name_plural": "Product Suppliers",
            },
        ),
        migrations.AddConstraint(
            model_name="productsupplier",
            constraint=models.UniqueConstraint(fields=("product", "supplier"), name="uniq_product_supplier"),
        ),
        migrations.AddConstraint(
            model_name="productsupplier",
            constraint=models.UniqueConstraint(
                fields=("product",),
                condition=models.Q(is_primary=True),
                name="uniq_product_primary_supplier",
            ),
        ),
    ]
