# Generated by ChatGPT on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_wholesale_customer",
            field=models.BooleanField(default=False),
        ),
    ]
