# Generated by Django 6.0.3 on 2026-04-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_route'),
        ('customers', '0003_customer_can_view_balance_customer_user'),
    ]

    operations = [
    ]
