# Generated by Django 6.0.2 on 2026-03-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='branch',
            table='branches',
        ),
        migrations.AlterModelTable(
            name='business',
            table='businesses',
        ),
    ]
