# Generated by Django 6.0 on 2026-03-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_branch_table_alter_business_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'branches'},
        ),
    ]
