# Generated by Django 6.0 on 2026-03-12 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_branch_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'businesses'},
        ),
    ]
