# Generated by ChatGPT on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_alter_saleitem_sale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
