# Generated by ChatGPT on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_alter_sale_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="sale_type",
            field=models.CharField(choices=[("retail", "Retail"), ("wholesale", "Wholesale")], default="retail", max_length=20),
        ),
        migrations.AlterField(
            model_name="sale",
            name="status",
            field=models.CharField(choices=[("draft", "Draft"), ("held", "Held"), ("completed", "Completed"), ("cancelled", "Cancelled")], default="draft", max_length=20),
        ),
    ]
