# Generated by ChatGPT on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_add_sale_type_and_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="price_type_used",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="pricing_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
