# Generated by ChatGPT on 2026-03-26

import django.db.models.deletion
from django.db import migrations, models


def backfill_saleitem_units(apps, schema_editor):
    SaleItem = apps.get_model("sales", "SaleItem")
    ProductUnit = apps.get_model("inventory", "ProductUnit")

    for item in SaleItem.objects.filter(product_unit__isnull=True):
        base_unit = ProductUnit.objects.filter(product_id=item.product_id, is_base_unit=True).first()
        if not base_unit:
            continue
        item.product_unit_id = base_unit.id
        item.conversion_snapshot = base_unit.conversion_to_base_unit
        item.base_quantity = item.quantity * base_unit.conversion_to_base_unit
        item.save(update_fields=["product_unit", "conversion_snapshot", "base_quantity"])


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_add_product_unit"),
        ("sales", "0005_add_saleitem_pricing_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="product_unit",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="sale_items", to="inventory.productunit"),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="conversion_snapshot",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="base_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_saleitem_units, migrations.RunPython.noop),
    ]
