# Generated by Django 6.0 on 2026-03-26

import uuid
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_credit_fields(apps, schema_editor):
    Sale = apps.get_model("sales", "Sale")
    today = django.utils.timezone.localdate()
    for sale in Sale.objects.all():
        balance_due = sale.balance
        status = "paid"
        if balance_due > 0:
            if sale.amount_paid > 0:
                status = "partial"
            else:
                status = "unpaid"
            if getattr(sale, "is_credit_sale", False) and sale.due_date and sale.due_date < today:
                status = "overdue"
        sale.balance_due = balance_due
        sale.payment_status = status
        sale.save(update_fields=["balance_due", "payment_status"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_backfill_username"),
        ("sales", "0006_add_saleitem_unit_fields"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="is_credit_sale",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sale",
            name="payment_mode",
            field=models.CharField(blank=True, choices=[("cash", "Cash"), ("mobile_money", "Mobile Money"), ("card", "Card"), ("bank", "Bank Transfer"), ("credit", "Credit")], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="payment_status",
            field=models.CharField(choices=[("unpaid", "Unpaid"), ("partial", "Partial"), ("paid", "Paid"), ("overdue", "Overdue")], default="paid", max_length=20),
        ),
        migrations.AddField(
            model_name="sale",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="assigned_to",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_sales", to="accounts.user"),
        ),
        migrations.AddField(
            model_name="sale",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="balance_due",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name="SalePayment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("correlation_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_method", models.CharField(blank=True, max_length=50, null=True)),
                ("payment_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("reference", models.CharField(blank=True, default="", max_length=120)),
                ("note", models.TextField(blank=True, default="")),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="customers.customer")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_%(class)s_set", to=settings.AUTH_USER_MODEL)),
                ("received_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="received_payments", to="accounts.user")),
                ("sale", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="sales.sale")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_%(class)s_set", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-payment_date"],
            },
        ),
        migrations.RunPython(backfill_credit_fields, migrations.RunPython.noop),
    ]
