# Generated by Django 6.0.3 on 2026-04-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_sale_payment_mpesa_stk_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('mobile_money', 'Mobile Money'), ('card', 'Card'), ('bank', 'Bank Transfer'), ('credit', 'Credit')], max_length=20, null=True),
        ),
    ]
